### PR TITLE
User Login & User Creation

### PR DESCRIPTION
**Pull request by elinlim22**
1. Renamed app name : `social_login`
2. URLs set : `accounts/{social login site name}/login` & `accounts/{social login site name}/login/callback`
3. Created `views.py` with `APIView` class
4. Some additional settings added for DRF
5. `status_message` field added to `models.py`

### CODE REVIEW

**Comment by min3m** [comment]
good

**Review by 42jeelee — COMMENTED** [review]
LGTM👍

**Review by 42jeelee — APPROVED** [review]
LGTM 👍

**Review by min3m — APPROVED** [review]
goood

**Pull request merged**
